# Dogs Dataset with Keras #
workalong with week 9 & 10 lecture

In [1]:
# For neural networks.
import keras as kr
# For data frames.
import pandas as pd
# For numerical arrays.
import numpy as np
# For preprocessing data.
import sklearn.preprocessing as pre
# For splitting data sets.
import sklearn.model_selection as mod
# For whitening.
import sklearn.decomposition as dec

Using TensorFlow backend.


## Preparing

In [2]:
df = pd.read_csv("data/dogs.csv")
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
5    True    5   14.11    26.9        12
6   False    8    9.51    49.2        15
7    True    3   15.60    49.9        11
8    True    4   12.36    48.1        13
9   False    5   19.18    54.2        10
10  False    5   15.98    57.2        12
11   True    6    4.85    56.7        17
12  False    3   19.52    43.0        10
13  False    3   11.21    57.2        14
14   True    1   14.08    47.7        12
15   True    4   14.96    59.3        11
16   True    3    6.84    42.5        16
17  False    8   15.76    46.8        12
18  False    7   17.78    39.8        11
19  False    2   21.49    59.5        10
20  False    5   16.26    42.8        12
21  False    3   17.82    45.1        11
22   True    6    7.90    44.1        15
23  False    5   18.26    50.4        11
24  False    3   18.56    61.0        11
25  False    4   11.95    54.9        14
26  False    4   11.09    46.1        15
27   True    8   15.57    48.0        11
28  False    2    6.97    40.1        17
29  False    5   19.78    49.0        10
..    ...  ...     ...     ...       ...
70   True    3   15.49    41.9        11
71  False    5    8.84    53.4        16
72  False    2   13.85    36.0        13
73  False    0   17.10    60.3        12
74  False    3   16.12    28.4        12
75   True    0    3.67    46.9        18
76  False    2   14.98    46.7        12
77  False    3    8.28    41.3        16
78   True    6   16.25    44.6        11
79   True    4   21.81    52.0         8
80   True    6   21.88    43.0         8
81   True    6   14.21    63.4        12
82  False    3    5.05    55.7        18
83   True    4   19.55    41.0         9
84   True    5    6.60    48.1        16
85  False    6   13.39    65.1        13
86   True    4   20.90    52.0         9
87  False    2    8.02    48.2        16
88   True    3   19.38    63.5         9
89   True    6   16.52    51.5        11
90  False    7    9.02    58.3        16
91  False    6   13.38    63.3        13
92   True    1   21.50    55.7         8
93   True    6   10.55    44.6        14
94  False    4   11.00    43.7        15
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

Keras works best with numerical data rather than categorical. Best to encode categorical data to make it look like a number.

In [3]:
# Week 9 method
# df["ispure"] = df["pure"].astype(np.int) # adding column where it is encoded

# Other way
# df["ispure"]=(df["pure"] == True).astype(np.int)
# df["isnotpure"] = (df["pure"] == False).astype(np.int)
# df

# Week 10 method - using the SKLearn Preprocessing binarizer
pureenc = pre.LabelBinarizer()
pureenc.fit(df['pure'])
df['pureenc'] = pureenc.transform(df['pure'])


In [4]:
# Week 9
# Create the inputs for keras
# inputs = df[["age", "weight", "height", "ispure", "isnotpure"]]
# inputs

# Week 10
x = df[['pureenc', 'age', 'weight', 'height']]
y = df['lifespan']

x

pureenc  age  weight  height
0         1    3    7.94    49.6
1         1    7    5.05    63.5
2         1    6   16.15    68.2
3         0    3   15.50    64.7
4         0    3   12.17    59.7
5         1    5   14.11    26.9
6         0    8    9.51    49.2
7         1    3   15.60    49.9
8         1    4   12.36    48.1
9         0    5   19.18    54.2
10        0    5   15.98    57.2
11        1    6    4.85    56.7
12        0    3   19.52    43.0
13        0    3   11.21    57.2
14        1    1   14.08    47.7
15        1    4   14.96    59.3
16        1    3    6.84    42.5
17        0    8   15.76    46.8
18        0    7   17.78    39.8
19        0    2   21.49    59.5
20        0    5   16.26    42.8
21        0    3   17.82    45.1
22        1    6    7.90    44.1
23        0    5   18.26    50.4
24        0    3   18.56    61.0
25        0    4   11.95    54.9
26        0    4   11.09    46.1
27        1    8   15.57    48.0
28        0    2    6.97    40.1
29        0    5   19.78    49.0
..      ...  ...     ...     ...
70        1    3   15.49    41.9
71        0    5    8.84    53.4
72        0    2   13.85    36.0
73        0    0   17.10    60.3
74        0    3   16.12    28.4
75        1    0    3.67    46.9
76        0    2   14.98    46.7
77        0    3    8.28    41.3
78        1    6   16.25    44.6
79        1    4   21.81    52.0
80        1    6   21.88    43.0
81        1    6   14.21    63.4
82        0    3    5.05    55.7
83        1    4   19.55    41.0
84        1    5    6.60    48.1
85        0    6   13.39    65.1
86        1    4   20.90    52.0
87        0    2    8.02    48.2
88        1    3   19.38    63.5
89        1    6   16.52    51.5
90        0    7    9.02    58.3
91        0    6   13.38    63.3
92        1    1   21.50    55.7
93        1    6   10.55    44.6
94        0    4   11.00    43.7
95        0    4   20.76    52.2
96        0    4   17.40    47.5
97        0    6   15.60    51.4
98        0    3    8.37    54.1
99        1    7    9.09    50.3

[100 rows x 4 columns]

In [5]:
# Week 9
# And the outputs
# output = df["lifespan"]
# output

# Week 10
y

0     15
1     17
2     11
3     12
4     14
5     12
6     15
7     11
8     13
9     10
10    12
11    17
12    10
13    14
14    12
15    11
16    16
17    12
18    11
19    10
20    12
21    11
22    15
23    11
24    11
25    14
26    15
27    11
28    17
29    10
      ..
70    11
71    16
72    13
73    12
74    12
75    18
76    12
77    16
78    11
79     8
80     8
81    12
82    18
83     9
84    16
85    13
86     9
87    16
88     9
89    11
90    16
91    13
92     8
93    14
94    15
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [6]:
# Split the dataset into training and testing
x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)

## Building and training

In [7]:
m = kr.models.Sequential()

# Week 9
#m.add(kr.layers.Dense(10, input_dim=5, activation = "linear"))
#m.add(kr.layers.Dense(50, activation = "sigmoid"))
#m.add(kr.layers.Dense(10, activation = "linear"))
#m.add(kr.layers.Dense(10, activation = "linear"))
#m.add(kr.layers.Dense(1, activation = "linear"))

# Week 10
m.add(kr.layers.Dense(20, input_dim=4, activation = "relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss = "mean_squared_error", optimizer ="adam")

In [8]:
# Week 9
# m.fit(inputs, output, epochs=50, batch_size=10)

# Week 10
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 32.5606
Epoch 2/100
70/70 [==============================] - 0s 114us/step - loss: 18.9825
Epoch 3/100
70/70 [==============================] - 0s 99us/step - loss: 11.9334
Epoch 4/100
70/70 [==============================] - 0s 100us/step - loss: 9.4837
Epoch 5/100
70/70 [==============================] - 0s 114us/step - loss: 9.7110
Epoch 6/100
70/70 [==============================] - 0s 100us/step - loss: 9.8447
Epoch 7/100
70/70 [==============================] - 0s 99us/step - loss: 9.6446
Epoch 8/100
70/70 [==============================] - 0s 100us/step - loss: 9.3727
Epoch 9/100
70/70 [==============================] - 0s 100us/step - loss: 9.2849
Epoch 10/100
70/70 [==============================] - 0s 114us/step - loss: 9.2578
Epoch 11/100
70/70 [==============================] - 0s 100us/step - loss: 9.2270
Epoch 12/100
70/70 [==============================] - 0s 100us/step - loss: 9.1721
Epoch 13/100
7

70/70 [==============================] - 0s 71us/step - loss: 7.2153


In [9]:
# Week 9
# m.predict(inputs)

# Week 10
m.predict(x_test).round().T

array([[14., 12.,  9.,  9.,  9., 10., 13., 14., 13., 11., 10., 12.,  8.,
        11., 14., 15., 11.,  8.,  7., 12., 10., 14., 15., 10., 15., 11.,
        14., 10., 12., 13.]], dtype=float32)

In [10]:
# Week 9
# output.as_matrix()

# Week 10
y_test.as_matrix().astype(np.float32)

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


array([15., 15., 10., 13., 10., 11., 11., 11.,  9.,  9., 11., 11., 11.,
       11., 19., 13., 10., 13., 12., 10., 15., 14., 14., 11., 16., 13.,
       18., 11., 10., 13.], dtype=float32)

In [11]:
# Week 9
# np.around(m.predict(inputs).T)

# Week 10
# Calculate the loss function (Mean squared error in our case)
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 665us/step


6.874843120574951

In [12]:
# Week 9 
# Mean squared value
# np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

## Scaling

In [13]:
# Adding a scaler
scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

In [14]:
# Rebuild the neural network
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [15]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 272.8988
Epoch 2/100
70/70 [==============================] - 0s 93us/step - loss: 211.2705
Epoch 3/100
70/70 [==============================] - 0s 99us/step - loss: 161.8239
Epoch 4/100
70/70 [==============================] - 0s 99us/step - loss: 121.0273
Epoch 5/100
70/70 [==============================] - 0s 71us/step - loss: 89.2137
Epoch 6/100
70/70 [==============================] - 0s 85us/step - loss: 64.2871
Epoch 7/100
70/70 [==============================] - 0s 99us/step - loss: 45.5818
Epoch 8/100
70/70 [==============================] - 0s 100us/step - loss: 32.3849
Epoch 9/100
70/70 [==============================] - 0s 86us/step - loss: 23.4601
Epoch 10/100
70/70 [==============================] - 0s 99us/step - loss: 17.1002
Epoch 11/100
70/70 [==============================] - 0s 114us/step - loss: 13.2300
Epoch 12/100
70/70 [==============================] - 0s 99us/step - loss: 11.3831
Epoch 13

70/70 [==============================] - 0s 71us/step - loss: 7.8269


In [16]:
m.predict(x_test).round().T

array([[14., 12.,  9.,  9.,  9., 10., 13., 14., 14., 11.,  9., 12.,  8.,
        11., 13., 16., 12.,  7.,  7., 12., 11., 14., 14.,  9., 14., 12.,
        12., 10., 11., 13.]], dtype=float32)

In [17]:
y_test.as_matrix().astype(np.float32)

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([15., 15., 10., 13., 10., 11., 11., 11.,  9.,  9., 11., 11., 11.,
       11., 19., 13., 10., 13., 12., 10., 15., 14., 14., 11., 16., 13.,
       18., 11., 10., 13.], dtype=float32)

In [18]:
m.evaluate(x_test, y_test)
# Shows improvement from not standardised

30/30 [==============================] - 0s 664us/step


8.679686546325684

## Whitening

In [19]:
pca = dec.PCA(n_components=4, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

pureenc       age    weight    height
0   2.299354 -0.240448 -0.434819 -1.195808
1   0.328706  0.054662 -0.076606  1.018673
2   0.518867  0.536074 -0.507373 -1.036295
3  -1.104962 -1.063266 -0.743208 -0.786807
4   0.235560 -0.339201  1.816853  1.082677
5   0.154108  1.008635 -0.983778  0.976711
6   1.176460 -0.173312 -0.993948 -1.085179
7   0.212164 -0.574092  0.835568 -0.925693
8  -0.722316  1.876685  0.945429  1.069407
9  -1.435508  1.763921  1.367506  1.161423
10  0.198635  2.339762 -0.882664  0.911847
11 -0.357028  1.063538  0.432230 -0.946343
12  0.943171 -1.567518 -0.633436  1.015644
13  0.717982  0.701584  1.448496 -1.029433
14  1.088215 -0.559349  2.347344 -0.995008
15 -0.147994 -1.677560 -0.238681  1.148830
16 -0.944575 -0.286671 -0.194419  1.173162
17  3.503231 -1.255911 -1.871010  0.694862
18  0.419901  0.659198 -0.023226 -1.022014
19 -0.872901  0.965773  1.352078 -0.867541
20 -0.722090 -0.492345  0.291249 -0.836331
21  0.271697  0.029408 -1.529515  0.998984
22 -1.380937 -0.178941  0.746328  1.234015
23 -0.155458 -1.213464  1.726389 -0.838674
24  0.598257 -0.438534  0.871359  1.029494
25  0.263472  0.694769 -0.514302 -1.015547
26  0.154657 -1.225333  0.301197 -0.899075
27 -0.392945 -1.145918  0.267162 -0.842830
28  1.376797 -0.683845  1.874614  0.973534
29 -1.729533 -0.478353  0.216630  1.276575
..       ...       ...       ...       ...
40  0.361561 -0.369558  1.826086 -0.933196
41  0.188503  1.590917  0.508440  0.973764
42  0.911455  1.309190 -0.421942 -1.114032
43 -0.574666 -0.513398  0.300436 -0.851488
44 -0.174420 -1.456866 -0.222089 -0.861707
45  0.044920 -0.328613 -0.607751  1.057933
46  0.378374 -0.160941 -1.051152 -0.998548
47  0.882599 -0.230784 -0.539561  0.962009
48 -0.033780  1.026324  1.415342  1.041534
49 -0.610083  1.393149 -1.011152  1.042865
50 -1.874863 -0.636728  0.676703  1.308609
51 -0.117822 -0.364407  0.826957 -0.899094
52  0.235182 -0.954355 -0.157605  1.074371
53  0.890581 -0.793007  0.386572 -0.998960
54  1.630896  1.396761  0.599194  0.824937
55 -0.998358  0.309644 -0.634501 -0.860336
56  1.433015  0.359278  0.508503  0.893319
57 -0.593993  0.308275 -2.052058 -0.931506
58 -0.532118 -1.625165 -1.709700  1.161377
59  0.040866  1.305458 -0.487900  0.984722
60  0.791976 -1.622623  0.798404  1.061702
61 -0.612248  1.863128 -0.492164 -0.972539
62  0.779663  1.605748 -0.412024  0.890475
63 -1.374912 -0.002308  0.762044 -0.778081
64 -1.134419 -1.406286  0.676327 -0.741071
65 -1.898770 -0.282375 -0.743595 -0.735283
66  0.571851  0.775343  0.958688  0.977664
67 -1.506800 -0.446017 -0.727085 -0.770729
68  0.787946 -0.418048  0.406668 -1.004648
69  1.032772  1.606259 -0.873566 -1.149694

[70 rows x 4 columns]

In [20]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(100, input_dim=4, activation="tanh"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [22]:
m.fit(x_train_white, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 162.2287
Epoch 2/100
70/70 [==============================] - 0s 100us/step - loss: 159.7779
Epoch 3/100
70/70 [==============================] - 0s 85us/step - loss: 156.7659
Epoch 4/100
70/70 [==============================] - 0s 71us/step - loss: 154.2298
Epoch 5/100
70/70 [==============================] - 0s 114us/step - loss: 151.4246
Epoch 6/100
70/70 [==============================] - 0s 100us/step - loss: 148.5282
Epoch 7/100
70/70 [==============================] - 0s 114us/step - loss: 145.6523
Epoch 8/100
70/70 [==============================] - 0s 85us/step - loss: 142.6047
Epoch 9/100
70/70 [==============================] - 0s 100us/step - loss: 139.4618
Epoch 10/100
70/70 [==============================] - 0s 100us/step - loss: 136.2659
Epoch 11/100
70/70 [==============================] - 0s 114us/step - loss: 132.7544
Epoch 12/100
70/70 [==============================] - 0s 100us/step - loss: 128

70/70 [==============================] - 0s 99us/step - loss: 0.2047
Epoch 100/100
70/70 [==============================] - 0s 86us/step - loss: 0.2038


In [23]:
m.predict(pca.transform(x_test)).round().T

array([[15., 15., 10., 13.,  9., 10., 11., 11.,  9.,  8., 11., 11., 11.,
        11., 17., 13., 10., 13., 12.,  9., 15., 15., 15., 11., 16., 13.,
        17., 11.,  8., 13.]], dtype=float32)

In [24]:
y_test.as_matrix().astype(np.float32)

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([15., 15., 10., 13., 10., 11., 11., 11.,  9.,  9., 11., 11., 11.,
       11., 19., 13., 10., 13., 12., 10., 15., 14., 14., 11., 16., 13.,
       18., 11., 10., 13.], dtype=float32)

In [25]:
m.evaluate(pca.transform(x_test), y_test)

30/30 [==============================] - 0s 697us/step


0.3813928961753845

## End