# Dogs Dataset with Keras #
workalong with week 9 lecture

In [3]:
import keras as kr
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/dogs.csv")
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
5    True    5   14.11    26.9        12
6   False    8    9.51    49.2        15
7    True    3   15.60    49.9        11
8    True    4   12.36    48.1        13
9   False    5   19.18    54.2        10
10  False    5   15.98    57.2        12
11   True    6    4.85    56.7        17
12  False    3   19.52    43.0        10
13  False    3   11.21    57.2        14
14   True    1   14.08    47.7        12
15   True    4   14.96    59.3        11
16   True    3    6.84    42.5        16
17  False    8   15.76    46.8        12
18  False    7   17.78    39.8        11
19  False    2   21.49    59.5        10
20  False    5   16.26    42.8        12
21  False    3   17.82    45.1        11
22   True    6    7.90    44.1        15
23  False    5   18.26    50.4        11
24  False    3   18.56    61.0        11
25  False    4   11.95    54.9        14
26  False    4   11.09    46.1        15
27   True    8   15.57    48.0        11
28  False    2    6.97    40.1        17
29  False    5   19.78    49.0        10
..    ...  ...     ...     ...       ...
70   True    3   15.49    41.9        11
71  False    5    8.84    53.4        16
72  False    2   13.85    36.0        13
73  False    0   17.10    60.3        12
74  False    3   16.12    28.4        12
75   True    0    3.67    46.9        18
76  False    2   14.98    46.7        12
77  False    3    8.28    41.3        16
78   True    6   16.25    44.6        11
79   True    4   21.81    52.0         8
80   True    6   21.88    43.0         8
81   True    6   14.21    63.4        12
82  False    3    5.05    55.7        18
83   True    4   19.55    41.0         9
84   True    5    6.60    48.1        16
85  False    6   13.39    65.1        13
86   True    4   20.90    52.0         9
87  False    2    8.02    48.2        16
88   True    3   19.38    63.5         9
89   True    6   16.52    51.5        11
90  False    7    9.02    58.3        16
91  False    6   13.38    63.3        13
92   True    1   21.50    55.7         8
93   True    6   10.55    44.6        14
94  False    4   11.00    43.7        15
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

Keras works best with numerical data rather than categorical. Best to encode categorical data to make it look like a number.

In [8]:
df["ispure"] = df["pure"].astype(np.int) # adding column where it is encoded

# Other way
df["ispure"]=(df["pure"] == True).astype(np.int)
df["isnotpure"] = (df["pure"] == False).astype(np.int)
df

pure  age  weight  height  lifespan  ispure  isnotpure
0    True    3    7.94    49.6        15       1          0
1    True    7    5.05    63.5        17       1          0
2    True    6   16.15    68.2        11       1          0
3   False    3   15.50    64.7        12       0          1
4   False    3   12.17    59.7        14       0          1
5    True    5   14.11    26.9        12       1          0
6   False    8    9.51    49.2        15       0          1
7    True    3   15.60    49.9        11       1          0
8    True    4   12.36    48.1        13       1          0
9   False    5   19.18    54.2        10       0          1
10  False    5   15.98    57.2        12       0          1
11   True    6    4.85    56.7        17       1          0
12  False    3   19.52    43.0        10       0          1
13  False    3   11.21    57.2        14       0          1
14   True    1   14.08    47.7        12       1          0
15   True    4   14.96    59.3        11       1          0
16   True    3    6.84    42.5        16       1          0
17  False    8   15.76    46.8        12       0          1
18  False    7   17.78    39.8        11       0          1
19  False    2   21.49    59.5        10       0          1
20  False    5   16.26    42.8        12       0          1
21  False    3   17.82    45.1        11       0          1
22   True    6    7.90    44.1        15       1          0
23  False    5   18.26    50.4        11       0          1
24  False    3   18.56    61.0        11       0          1
25  False    4   11.95    54.9        14       0          1
26  False    4   11.09    46.1        15       0          1
27   True    8   15.57    48.0        11       1          0
28  False    2    6.97    40.1        17       0          1
29  False    5   19.78    49.0        10       0          1
..    ...  ...     ...     ...       ...     ...        ...
70   True    3   15.49    41.9        11       1          0
71  False    5    8.84    53.4        16       0          1
72  False    2   13.85    36.0        13       0          1
73  False    0   17.10    60.3        12       0          1
74  False    3   16.12    28.4        12       0          1
75   True    0    3.67    46.9        18       1          0
76  False    2   14.98    46.7        12       0          1
77  False    3    8.28    41.3        16       0          1
78   True    6   16.25    44.6        11       1          0
79   True    4   21.81    52.0         8       1          0
80   True    6   21.88    43.0         8       1          0
81   True    6   14.21    63.4        12       1          0
82  False    3    5.05    55.7        18       0          1
83   True    4   19.55    41.0         9       1          0
84   True    5    6.60    48.1        16       1          0
85  False    6   13.39    65.1        13       0          1
86   True    4   20.90    52.0         9       1          0
87  False    2    8.02    48.2        16       0          1
88   True    3   19.38    63.5         9       1          0
89   True    6   16.52    51.5        11       1          0
90  False    7    9.02    58.3        16       0          1
91  False    6   13.38    63.3        13       0          1
92   True    1   21.50    55.7         8       1          0
93   True    6   10.55    44.6        14       1          0
94  False    4   11.00    43.7        15       0          1
95  False    4   20.76    52.2        10       0          1
96  False    4   17.40    47.5        11       0          1
97  False    6   15.60    51.4        12       0          1
98  False    3    8.37    54.1        16       0          1
99   True    7    9.09    50.3        14       1          0

[100 rows x 7 columns]

In [9]:
# Create the inputs for keras
inputs = df[["age", "weight", "height", "ispure", "isnotpure"]]
inputs

age  weight  height  ispure  isnotpure
0     3    7.94    49.6       1          0
1     7    5.05    63.5       1          0
2     6   16.15    68.2       1          0
3     3   15.50    64.7       0          1
4     3   12.17    59.7       0          1
5     5   14.11    26.9       1          0
6     8    9.51    49.2       0          1
7     3   15.60    49.9       1          0
8     4   12.36    48.1       1          0
9     5   19.18    54.2       0          1
10    5   15.98    57.2       0          1
11    6    4.85    56.7       1          0
12    3   19.52    43.0       0          1
13    3   11.21    57.2       0          1
14    1   14.08    47.7       1          0
15    4   14.96    59.3       1          0
16    3    6.84    42.5       1          0
17    8   15.76    46.8       0          1
18    7   17.78    39.8       0          1
19    2   21.49    59.5       0          1
20    5   16.26    42.8       0          1
21    3   17.82    45.1       0          1
22    6    7.90    44.1       1          0
23    5   18.26    50.4       0          1
24    3   18.56    61.0       0          1
25    4   11.95    54.9       0          1
26    4   11.09    46.1       0          1
27    8   15.57    48.0       1          0
28    2    6.97    40.1       0          1
29    5   19.78    49.0       0          1
..  ...     ...     ...     ...        ...
70    3   15.49    41.9       1          0
71    5    8.84    53.4       0          1
72    2   13.85    36.0       0          1
73    0   17.10    60.3       0          1
74    3   16.12    28.4       0          1
75    0    3.67    46.9       1          0
76    2   14.98    46.7       0          1
77    3    8.28    41.3       0          1
78    6   16.25    44.6       1          0
79    4   21.81    52.0       1          0
80    6   21.88    43.0       1          0
81    6   14.21    63.4       1          0
82    3    5.05    55.7       0          1
83    4   19.55    41.0       1          0
84    5    6.60    48.1       1          0
85    6   13.39    65.1       0          1
86    4   20.90    52.0       1          0
87    2    8.02    48.2       0          1
88    3   19.38    63.5       1          0
89    6   16.52    51.5       1          0
90    7    9.02    58.3       0          1
91    6   13.38    63.3       0          1
92    1   21.50    55.7       1          0
93    6   10.55    44.6       1          0
94    4   11.00    43.7       0          1
95    4   20.76    52.2       0          1
96    4   17.40    47.5       0          1
97    6   15.60    51.4       0          1
98    3    8.37    54.1       0          1
99    7    9.09    50.3       1          0

[100 rows x 5 columns]

In [10]:
# And the outputs
output = df["lifespan"]
output

0     15
1     17
2     11
3     12
4     14
5     12
6     15
7     11
8     13
9     10
10    12
11    17
12    10
13    14
14    12
15    11
16    16
17    12
18    11
19    10
20    12
21    11
22    15
23    11
24    11
25    14
26    15
27    11
28    17
29    10
      ..
70    11
71    16
72    13
73    12
74    12
75    18
76    12
77    16
78    11
79     8
80     8
81    12
82    18
83     9
84    16
85    13
86     9
87    16
88     9
89    11
90    16
91    13
92     8
93    14
94    15
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [43]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(10, input_dim=5, activation = "linear"))
m.add(kr.layers.Dense(50, activation = "sigmoid"))
m.add(kr.layers.Dense(10, activation = "linear"))
m.add(kr.layers.Dense(10, activation = "linear"))
m.add(kr.layers.Dense(1, activation = "linear"))

m.compile(loss = "mean_squared_error", optimizer ="adam")

In [44]:
m.fit(inputs, output, epochs=50, batch_size=10)

Epoch 1/50
100/100 [==============================] - 0s 5ms/step - loss: 109.8406
Epoch 2/50
100/100 [==============================] - 0s 189us/step - loss: 70.1993
Epoch 3/50
100/100 [==============================] - 0s 160us/step - loss: 35.7684
Epoch 4/50
100/100 [==============================] - 0s 160us/step - loss: 12.9963
Epoch 5/50
100/100 [==============================] - 0s 169us/step - loss: 6.1391
Epoch 6/50
100/100 [==============================] - 0s 160us/step - loss: 6.9220
Epoch 7/50
100/100 [==============================] - 0s 160us/step - loss: 6.7244
Epoch 8/50
100/100 [==============================] - 0s 160us/step - loss: 6.3226
Epoch 9/50
100/100 [==============================] - 0s 160us/step - loss: 6.3308
Epoch 10/50
100/100 [==============================] - 0s 150us/step - loss: 6.1555
Epoch 11/50
100/100 [==============================] - 0s 180us/step - loss: 5.9898
Epoch 12/50
100/100 [==============================] - 0s 170us/step - loss: 5.863

In [18]:
m.predict(inputs)

array([[13.071423  ],
       [18.167614  ],
       [17.216265  ],
       [16.375368  ],
       [15.586656  ],
       [ 5.5795493 ],
       [13.734457  ],
       [11.656561  ],
       [11.903367  ],
       [12.888523  ],
       [14.380552  ],
       [16.11585   ],
       [ 9.331822  ],
       [15.054121  ],
       [11.05892   ],
       [14.622482  ],
       [11.240251  ],
       [11.817599  ],
       [ 9.273066  ],
       [13.571619  ],
       [10.174471  ],
       [10.270405  ],
       [11.885753  ],
       [11.973385  ],
       [14.708984  ],
       [14.376712  ],
       [12.008427  ],
       [11.768076  ],
       [10.824926  ],
       [11.271879  ],
       [10.713086  ],
       [11.274223  ],
       [ 9.731796  ],
       [13.381671  ],
       [ 8.052582  ],
       [ 9.806468  ],
       [14.855473  ],
       [11.490906  ],
       [12.595772  ],
       [11.31521   ],
       [11.469336  ],
       [14.046262  ],
       [ 8.245036  ],
       [15.415737  ],
       [12.597561  ],
       [13

In [19]:
output.as_matrix()

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([15, 17, 11, 12, 14, 12, 15, 11, 13, 10, 12, 17, 10, 14, 12, 11, 16,
       12, 11, 10, 12, 11, 15, 11, 11, 14, 15, 11, 17, 10, 10, 11, 11, 19,
        8, 13, 16, 14, 10, 12, 12, 14, 10, 13, 14, 11, 15, 10, 15, 12, 13,
       12, 10, 11, 10, 11, 10, 14, 10, 11, 11, 11, 13, 19, 14, 14,  8, 12,
       11, 11, 11, 16, 13, 12, 12, 18, 12, 16, 11,  8,  8, 12, 18,  9, 16,
       13,  9, 16,  9, 11, 16, 13,  8, 14, 15, 10, 11, 12, 16, 14],
      dtype=int64)

In [26]:
np.around(m.predict(inputs).T)

array([[13., 18., 17., 16., 16.,  6., 14., 12., 12., 13., 14., 16.,  9.,
        15., 11., 15., 11., 12.,  9., 14., 10., 10., 12., 12., 15., 14.,
        12., 12., 11., 11., 11., 11., 10., 13.,  8., 10., 15., 11., 13.,
        11., 11., 14.,  8., 15., 13., 14., 12., 13.,  9.,  9., 18.,  9.,
        10., 12., 15., 13., 12., 12., 13.,  8., 10., 17., 14., 13., 12.,
        14.,  1., 14., 15., 13.,  9., 15.,  8., 14.,  6., 13., 11., 11.,
        10., 11.,  9., 16., 16.,  8., 13., 17., 11., 13., 15., 12., 16.,
        17., 12., 12., 11., 12., 11., 13., 15., 14.]], dtype=float32)

In [25]:
# Mean squared value
np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


30.49468060319207