# Dogs Dataset with Keras #
workalong with week 9 & 10 lecture

In [1]:
# For neural networks.
import keras as kr
# For data frames.
import pandas as pd
# For numerical arrays.
import numpy as np
# For preprocessing data.
import sklearn.preprocessing as pre
# For splitting data sets.
import sklearn.model_selection as mod
# For whitening.
import sklearn.decomposition as dec

Using TensorFlow backend.


## Preparing

In [2]:
df = pd.read_csv("data/dogs.csv")
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
5    True    5   14.11    26.9        12
6   False    8    9.51    49.2        15
7    True    3   15.60    49.9        11
8    True    4   12.36    48.1        13
9   False    5   19.18    54.2        10
10  False    5   15.98    57.2        12
11   True    6    4.85    56.7        17
12  False    3   19.52    43.0        10
13  False    3   11.21    57.2        14
14   True    1   14.08    47.7        12
15   True    4   14.96    59.3        11
16   True    3    6.84    42.5        16
17  False    8   15.76    46.8        12
18  False    7   17.78    39.8        11
19  False    2   21.49    59.5        10
20  False    5   16.26    42.8        12
21  False    3   17.82    45.1        11
22   True    6    7.90    44.1        15
23  False    5   18.26    50.4        11
24  False    3   18.56    61.0        11
25  False    4   11.95    54.9        14
26  False    4   11.09    46.1        15
27   True    8   15.57    48.0        11
28  False    2    6.97    40.1        17
29  False    5   19.78    49.0        10
..    ...  ...     ...     ...       ...
70   True    3   15.49    41.9        11
71  False    5    8.84    53.4        16
72  False    2   13.85    36.0        13
73  False    0   17.10    60.3        12
74  False    3   16.12    28.4        12
75   True    0    3.67    46.9        18
76  False    2   14.98    46.7        12
77  False    3    8.28    41.3        16
78   True    6   16.25    44.6        11
79   True    4   21.81    52.0         8
80   True    6   21.88    43.0         8
81   True    6   14.21    63.4        12
82  False    3    5.05    55.7        18
83   True    4   19.55    41.0         9
84   True    5    6.60    48.1        16
85  False    6   13.39    65.1        13
86   True    4   20.90    52.0         9
87  False    2    8.02    48.2        16
88   True    3   19.38    63.5         9
89   True    6   16.52    51.5        11
90  False    7    9.02    58.3        16
91  False    6   13.38    63.3        13
92   True    1   21.50    55.7         8
93   True    6   10.55    44.6        14
94  False    4   11.00    43.7        15
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

Keras works best with numerical data rather than categorical. Best to encode categorical data to make it look like a number.

In [3]:
# Week 9 method
# df["ispure"] = df["pure"].astype(np.int) # adding column where it is encoded

# Other way
# df["ispure"]=(df["pure"] == True).astype(np.int)
# df["isnotpure"] = (df["pure"] == False).astype(np.int)
# df

# Week 10 method - using the SKLearn Preprocessing binarizer
pureenc = pre.LabelBinarizer()
pureenc.fit(df['pure'])
df['pureenc'] = pureenc.transform(df['pure'])


In [4]:
# Week 9
# Create the inputs for keras
# inputs = df[["age", "weight", "height", "ispure", "isnotpure"]]
# inputs

# Week 10
x = df[['pureenc', 'age', 'weight', 'height']]
y = df['lifespan']

x

pureenc  age  weight  height
0         1    3    7.94    49.6
1         1    7    5.05    63.5
2         1    6   16.15    68.2
3         0    3   15.50    64.7
4         0    3   12.17    59.7
5         1    5   14.11    26.9
6         0    8    9.51    49.2
7         1    3   15.60    49.9
8         1    4   12.36    48.1
9         0    5   19.18    54.2
10        0    5   15.98    57.2
11        1    6    4.85    56.7
12        0    3   19.52    43.0
13        0    3   11.21    57.2
14        1    1   14.08    47.7
15        1    4   14.96    59.3
16        1    3    6.84    42.5
17        0    8   15.76    46.8
18        0    7   17.78    39.8
19        0    2   21.49    59.5
20        0    5   16.26    42.8
21        0    3   17.82    45.1
22        1    6    7.90    44.1
23        0    5   18.26    50.4
24        0    3   18.56    61.0
25        0    4   11.95    54.9
26        0    4   11.09    46.1
27        1    8   15.57    48.0
28        0    2    6.97    40.1
29        0    5   19.78    49.0
..      ...  ...     ...     ...
70        1    3   15.49    41.9
71        0    5    8.84    53.4
72        0    2   13.85    36.0
73        0    0   17.10    60.3
74        0    3   16.12    28.4
75        1    0    3.67    46.9
76        0    2   14.98    46.7
77        0    3    8.28    41.3
78        1    6   16.25    44.6
79        1    4   21.81    52.0
80        1    6   21.88    43.0
81        1    6   14.21    63.4
82        0    3    5.05    55.7
83        1    4   19.55    41.0
84        1    5    6.60    48.1
85        0    6   13.39    65.1
86        1    4   20.90    52.0
87        0    2    8.02    48.2
88        1    3   19.38    63.5
89        1    6   16.52    51.5
90        0    7    9.02    58.3
91        0    6   13.38    63.3
92        1    1   21.50    55.7
93        1    6   10.55    44.6
94        0    4   11.00    43.7
95        0    4   20.76    52.2
96        0    4   17.40    47.5
97        0    6   15.60    51.4
98        0    3    8.37    54.1
99        1    7    9.09    50.3

[100 rows x 4 columns]

In [5]:
# Week 9
# And the outputs
# output = df["lifespan"]
# output

# Week 10
y

0     15
1     17
2     11
3     12
4     14
5     12
6     15
7     11
8     13
9     10
10    12
11    17
12    10
13    14
14    12
15    11
16    16
17    12
18    11
19    10
20    12
21    11
22    15
23    11
24    11
25    14
26    15
27    11
28    17
29    10
      ..
70    11
71    16
72    13
73    12
74    12
75    18
76    12
77    16
78    11
79     8
80     8
81    12
82    18
83     9
84    16
85    13
86     9
87    16
88     9
89    11
90    16
91    13
92     8
93    14
94    15
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [6]:
# Split the dataset into training and testing
x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)

## Building and training

In [7]:
m = kr.models.Sequential()

# Week 9
#m.add(kr.layers.Dense(10, input_dim=5, activation = "linear"))
#m.add(kr.layers.Dense(50, activation = "sigmoid"))
#m.add(kr.layers.Dense(10, activation = "linear"))
#m.add(kr.layers.Dense(10, activation = "linear"))
#m.add(kr.layers.Dense(1, activation = "linear"))

# Week 10
m.add(kr.layers.Dense(20, input_dim=4, activation = "relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss = "mean_squared_error", optimizer ="adam")

In [8]:
# Week 9
# m.fit(inputs, output, epochs=50, batch_size=10)

# Week 10
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 3ms/step - loss: 194.6778
Epoch 2/100
70/70 [==============================] - 0s 100us/step - loss: 156.5017
Epoch 3/100
70/70 [==============================] - 0s 128us/step - loss: 121.9279
Epoch 4/100
70/70 [==============================] - 0s 185us/step - loss: 94.6161
Epoch 5/100
70/70 [==============================] - 0s 157us/step - loss: 72.4719
Epoch 6/100
70/70 [==============================] - 0s 100us/step - loss: 56.4147
Epoch 7/100
70/70 [==============================] - 0s 171us/step - loss: 43.7092
Epoch 8/100
70/70 [==============================] - 0s 114us/step - loss: 35.2737
Epoch 9/100
70/70 [==============================] - 0s 71us/step - loss: 28.9437
Epoch 10/100
70/70 [==============================] - 0s 214us/step - loss: 25.7834
Epoch 11/100
70/70 [==============================] - 0s 113us/step - loss: 23.6460
Epoch 12/100
70/70 [==============================] - 0s 100us/step - loss: 22.7188
E

70/70 [==============================] - 0s 128us/step - loss: 9.7248
Epoch 99/100
70/70 [==============================] - 0s 86us/step - loss: 9.6951
Epoch 100/100
70/70 [==============================] - 0s 142us/step - loss: 9.6402


In [9]:
# Week 9
# m.predict(inputs)

# Week 10
m.predict(x_test).round().T

array([[11., 14.,  2., 11., 13., 13., 17., 13., 11., 13., 14.,  9., 12.,
        14., 14., 13., 12., 13., 12., 11.,  7., 12., 15., 16., 12., 10.,
        13., 12., 13.,  9.]], dtype=float32)

In [10]:
# Week 9
# output.as_matrix()

# Week 10
y_test.as_matrix().astype(np.float32)

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


array([18., 11.,  8., 12., 12., 11., 11., 15., 14., 10., 12., 11., 11.,
       14., 12., 11.,  8., 10., 19., 11., 12., 14., 10., 12., 13.,  9.,
       11., 12., 14.,  8.], dtype=float32)

In [11]:
# Week 9
# np.around(m.predict(inputs).T)

# Week 10
# Calculate the loss function (Mean squared error in our case)
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 866us/step


10.938140869140625

In [12]:
# Week 9 
# Mean squared value
# np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

## Scaling

In [13]:
# Adding a scaler
scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

In [14]:
# Rebuild the neural network
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [15]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 3ms/step - loss: 55.0839
Epoch 2/100
70/70 [==============================] - 0s 157us/step - loss: 34.5147
Epoch 3/100
70/70 [==============================] - 0s 142us/step - loss: 22.0522
Epoch 4/100
70/70 [==============================] - 0s 128us/step - loss: 14.7188
Epoch 5/100
70/70 [==============================] - 0s 143us/step - loss: 12.1751
Epoch 6/100
70/70 [==============================] - 0s 156us/step - loss: 11.4302
Epoch 7/100
70/70 [==============================] - 0s 171us/step - loss: 11.4150
Epoch 8/100
70/70 [==============================] - 0s 228us/step - loss: 11.4835
Epoch 9/100
70/70 [==============================] - 0s 157us/step - loss: 11.3492
Epoch 10/100
70/70 [==============================] - 0s 143us/step - loss: 11.1293
Epoch 11/100
70/70 [==============================] - 0s 142us/step - loss: 10.9435
Epoch 12/100
70/70 [==============================] - 0s 157us/step - loss: 10.7635
Epo

70/70 [==============================] - 0s 100us/step - loss: 7.0973
Epoch 100/100
70/70 [==============================] - 0s 100us/step - loss: 7.1447


In [16]:
m.predict(x_test).round().T

array([[14., 14.,  4., 11., 13., 12., 17., 14., 11., 14., 13.,  9., 11.,
        14., 14., 13., 11., 12., 15., 11.,  7., 12., 14., 16., 12.,  9.,
        13., 13., 13.,  9.]], dtype=float32)

In [17]:
y_test.as_matrix().astype(np.float32)

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([18., 11.,  8., 12., 12., 11., 11., 15., 14., 10., 12., 11., 11.,
       14., 12., 11.,  8., 10., 19., 11., 12., 14., 10., 12., 13.,  9.,
       11., 12., 14.,  8.], dtype=float32)

In [18]:
m.evaluate(x_test, y_test)
# Shows improvement from not standardised

30/30 [==============================] - 0s 831us/step


7.3532915115356445

## Whitening

In [19]:
pca = dec.PCA(n_components=4, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

pureenc       age    weight    height
0  -1.571624 -1.105536 -0.179492  1.330266
1  -1.722759  0.204169  1.127897 -0.974274
2  -0.017611  1.026724  1.263744  0.911886
3  -0.929390  1.092281  1.373313 -1.107568
4   0.233654  1.508615  0.148905  1.007007
5  -0.464004  1.146601 -0.709897 -0.858819
6  -1.284191 -0.951349 -0.262491 -0.712831
7   1.534908  0.109203  0.171705  1.076649
8  -1.927151 -0.240313  0.742148  1.150873
9   0.604049  1.860121  0.022959 -1.049909
10  1.450913 -0.848452  1.836671  0.944535
11 -0.284647 -1.458344  0.168362 -0.760324
12 -1.126804 -1.591211 -0.688157 -0.609623
13 -0.657825  1.373107 -1.201198  1.223415
14 -0.165095 -0.630521  0.539846  1.149295
15  0.178693 -1.024300  0.048250  1.234025
16 -2.114376 -0.063372 -0.276288 -0.756954
17 -0.640381 -0.143022  0.017591 -0.838797
18 -1.517572  0.194423  1.098809 -0.976732
19  0.805485 -0.560005  0.367938 -0.898723
20  0.785320  0.593225  1.194938 -1.101500
21  0.604449 -0.530530  0.910941  1.066577
22 -1.565700 -0.266307 -1.313117  1.406299
23 -1.114850  0.384172 -0.494694 -0.800470
24  0.716474  0.538626 -0.290378 -0.902593
25  0.087182 -1.259589  0.583462 -0.843367
26 -0.503494 -1.099151  0.646686 -0.844726
27 -0.826734  0.569641 -0.566400 -0.816612
28  0.623338  0.668414  0.722337  0.989897
29  1.132406  1.335225 -1.478539 -0.829996
..       ...       ...       ...       ...
40  0.353635 -0.306157 -1.108058 -0.713722
41  1.576900 -0.138913 -1.316395 -0.742735
42  1.008224 -0.030274 -1.248425 -0.741124
43  0.863384  1.393891 -0.929922  1.134464
44  0.180968 -0.606866  0.969679 -0.951164
45  0.110013  0.942993  1.742792 -1.178452
46 -0.635360  1.855467 -0.794188 -0.901416
47 -1.074422 -0.189791  0.105808  1.199656
48  0.238998 -0.122121 -1.604587  1.370030
49 -0.971196  0.367274  2.009483  0.903417
50 -0.378050  1.070508  0.291772 -0.984857
51  1.790093  1.100808 -0.020007  1.009635
52 -0.072246 -1.271060 -0.895029 -0.645848
53 -0.736858  1.947016  0.727048  0.928838
54  0.319606 -0.045043 -0.124508  1.169513
55 -0.626377 -0.743734 -1.379213  1.422625
56  0.226920 -0.337739  1.940061  0.930361
57  0.764158 -1.271776 -0.518300 -0.723152
58  0.530446 -0.900371 -0.540999 -0.743311
59  0.442639  0.535495 -0.249057 -0.898284
60  0.995161  1.081266 -0.917372 -0.876553
61  0.268476  0.573750 -0.730360 -0.833309
62 -1.695755 -0.283347 -0.304629 -0.749219
63 -0.697381 -1.630185 -1.231261  1.480174
64  0.768151 -1.725283  1.071665  1.140249
65  1.149280 -0.663170  2.338047 -1.156502
66  2.625015 -0.210612  0.058700  1.080668
67  0.903104 -0.429509 -0.653294  1.250053
68 -1.508679  1.963402  1.340955  0.874578
69  1.150099 -0.872098  1.367605 -1.013605

[70 rows x 4 columns]

In [45]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(100, input_dim=4, activation="tanh"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [46]:
m.fit(x_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 152.9881
Epoch 2/100
70/70 [==============================] - 0s 100us/step - loss: 128.2698
Epoch 3/100
70/70 [==============================] - 0s 87us/step - loss: 106.6939
Epoch 4/100
70/70 [==============================] - 0s 71us/step - loss: 88.7085
Epoch 5/100
70/70 [==============================] - 0s 99us/step - loss: 72.9563
Epoch 6/100
70/70 [==============================] - 0s 100us/step - loss: 58.3367
Epoch 7/100
70/70 [==============================] - 0s 85us/step - loss: 44.2209
Epoch 8/100
70/70 [==============================] - 0s 100us/step - loss: 30.4892
Epoch 9/100
70/70 [==============================] - 0s 71us/step - loss: 20.3516
Epoch 10/100
70/70 [==============================] - 0s 86us/step - loss: 14.4588
Epoch 11/100
70/70 [==============================] - 0s 100us/step - loss: 11.3206
Epoch 12/100
70/70 [==============================] - 0s 100us/step - loss: 9.7681
Epoch 1

70/70 [==============================] - 0s 100us/step - loss: 1.1162


In [47]:
m.predict(x_test).round().T

array([[16., 12.,  9., 11., 12., 11., 13., 15., 13., 11., 12., 10., 11.,
        14., 12., 12., 10., 10., 16., 11., 10., 14., 11., 13., 12., 10.,
        11., 12., 13., 10.]], dtype=float32)

In [48]:
y_test.as_matrix().astype(np.float32)

C:\Users\ybrady\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([18., 11.,  8., 12., 12., 11., 11., 15., 14., 10., 12., 11., 11.,
       14., 12., 11.,  8., 10., 19., 11., 12., 14., 10., 12., 13.,  9.,
       11., 12., 14.,  8.], dtype=float32)

In [49]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 633us/step


1.3114161491394043

## End